### ISSUE TITLE
Recheck the math

### ISSUE THREAD

**Issue by micada** [pawar-2018/calculator#8]
Pretty straightforward.

With PR #4 the output of the calculator changed by a pretty significant factor. However this could be a number of things. A filing deadline passed, so we should look into what we're getting from Sunshine. A fair amount of work was done by @rbalik on the API, so maybe that changed, but also this side of the app might just need to be adjusted.

Let me know if you have any questions!

**Comment by lund5000** [comment]
https://expenditures.pawarapis.com/candidate/rauner responds with the following:
```
{
  expendituresCount: 11196,
  firstExpenditure: "2013-03-05T00:00:00",
  spendingDays: 1675,
  spentPerDay: "57399.27",
  spentPerSecond: "0.66",
  timestamp: "2017-10-05T16:05:22",
  total: "96143783.41"
}
```

At the time I write this it's closing in on 10PM, so 91.67% through the day. 91.67% of $57,399.27 is $52,616, and just as it turns 10:01PM the daily spend shows

![screen shot 2017-10-08 at 10 01 04 pm](https://user-images.githubusercontent.com/772939/31324073-41f07b20-ac74-11e7-9607-21708107532a.png)

The discrepancy for that and the other figures on the page can be explained by the precision of the `spentPerSecond` value returned from the API. Using the full value of 0.6643434028 closes the gap entirely, and even 0.6643 gets it down to seconds instead of minutes. 

But this discrepancy is less than 1% and only means a few hundred dollars or a handful of minutes off. The change did not come from the client-side JS.
